// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektHausmesse.Server.Data;

#nullable disable

namespace ProjektHausmesse.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250512073509_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ProjektHausmesse.Server.Data.ContainerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Position", "ProjektHausmesse.Server.Data.ContainerEntity.Position#Position", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("ProjektHausmesse.Server.Data.MeasurementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Distance")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("ProjektHausmesse.Server.Data.SensorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurDistance")
                        .HasColumnType("TEXT");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxDistance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("ProjektHausmesse.Server.Data.MeasurementEntity", b =>
                {
                    b.HasOne("ProjektHausmesse.Server.Data.SensorEntity", "Sensor")
                        .WithMany("Measurements")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("ProjektHausmesse.Server.Data.SensorEntity", b =>
                {
                    b.HasOne("ProjektHausmesse.Server.Data.ContainerEntity", "Container")
                        .WithOne("Sensor")
                        .HasForeignKey("ProjektHausmesse.Server.Data.SensorEntity", "ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("ProjektHausmesse.Server.Data.ContainerEntity", b =>
                {
                    b.Navigation("Sensor")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjektHausmesse.Server.Data.SensorEntity", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
